### ISSUE TITLE
Can't get cxd4 to work!

### ISSUE THREAD

**Issue by deathpancake** [mupen64plus/mupen64plus-rsp-cxd4#6]
First of all I apologize if this is the wrong place to put this because I have no idea where a better place to do so would be. I have an intel machine running windows 7 64bit, and I cannot for the life of me get cxd4 to work! I downloaded the latest version of mpy64 to get the plugins because I don't know how to compile code, and put it in my m64+ (newest version) folder. Then I went to the .cfg file in appdata roaming and changed the plugin names to the correct ones (I have tried it with all 3 cxd4 versions that come with m64py). Here's the weirdest part, it worked, and I was experimenting with games for a little bit, but then I was organizing my games and when I set all and .n64 files to open with mupen64plus.exe it stopped working. It couldn't find my games so I assumed that ".\" being the plugin path under ui-console meant directory where the actual game is located. So I changed the path from ".\" to my mupen directory. Now all plugins except cxd4 worked. In its place on the cmd prompt was "static interpreter 0.1.1". Confused, I put a game in the mupen directory and did the standard drag and drop, and still cxd4 wouldn't work. So I changed the directory back to ".\", and the same thing showed up. So then I deleted the .cfg and re-opened mupen, and when I set the plugin back to cxd4, it said something about no version number and then it said it set rsp back to default. Now no matter what I do it just says static interpreter instead of cxd4. I've tried re-downloading the plugins and mupen64+, and deleting the .cfg and appdata roaming mupen folder multiple times, but nothing works. please help!

**Comment by Narann** [comment]
Please post this in the mailing list. This place is for dev purpose, not support. :)
